# Generated by Django 2.0 on 2019-09-19 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='测站名称')),
                ('client_key', models.CharField(max_length=255, verbose_name='测站唯一索引')),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=12, null=True, verbose_name='经度')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=12, null=True, verbose_name='纬度')),
                ('topic', models.CharField(max_length=255, verbose_name='主题唯一索引')),
                ('description', models.TextField(null=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': '测站信息',
                'verbose_name_plural': '测站信息',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('key', models.CharField(max_length=255, verbose_name='下标')),
                ('value', models.CharField(max_length=255, null=True, verbose_name='值')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': '配置信息',
                'verbose_name_plural': '配置信息',
            },
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='标题')),
                ('key', models.CharField(max_length=255, verbose_name='下标')),
                ('topic', models.CharField(max_length=255, verbose_name='主题')),
                ('description', models.TextField(null=True, verbose_name='描述')),
                ('r_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lot.Clients', verbose_name='测站')),
            ],
            options={
                'verbose_name': '测站订阅主题信息',
                'verbose_name_plural': '测站订阅主题信息',
            },
        ),
    ]
