# Generated by Django 2.0 on 2019-09-19 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='r_client',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='lot.Clients', verbose_name='测站'),
        ),
    ]
