# Generated by Django 2.0 on 2019-09-20 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_r_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='r_client',
            field=models.ManyToManyField(to='lot.Clients'),
        ),
    ]
